# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('transfer', models.BooleanField(default=False)),
                ('reconciled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_account.ExternalAccount')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtransactions', to='transaction.Transaction')),
            ],
        ),
    ]
