# Generated by Django 3.0.8 on 2020-08-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_account', '0002_auto_20200816_1526'),
        ('category', '0003_remove_category_transactions'),
        ('transaction', '0002_auto_20200816_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='external_account.ExternalAccount'),
        ),
    ]
