# Generated by Django 3.0.8 on 2020-08-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200823_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='transfer_acct', to='external_account.ExternalAccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='num',
            field=models.IntegerField(help_text='Used to record check numbers', null=True),
        ),
    ]
