# Generated by Django 3.0.8 on 2020-08-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200823_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='num',
            field=models.CharField(help_text='Used to record check numbers', max_length=10, null=True),
        ),
    ]
