# Generated by Django 3.0.7 on 2020-06-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'Patelco')], max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
