# Generated by Django 3.0.8 on 2020-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='name',
            field=models.CharField(choices=[('patelco', 'Patelco')], max_length=100),
        ),
    ]
