# Generated by Django 3.0.8 on 2020-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_account', '0002_auto_20200816_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='name',
            field=models.CharField(choices=[('patelco', 'Patelco')], max_length=100, unique=True),
        ),
    ]
